# frozen_string_literal: true

source 'https://rubygems.org'

gemspec
gem 'bundle'
gem 'mixlib-shellout'
gem 'thor'

group :build do
  gem 'rake', '>=12.0.0'
  gem 'rspec-core'
end
group :development do
  gem 'rspec'
  gem 'rake-notes'
  gem 'rubocop'
  gem 'rubocop-rspec'
end
