FROM ruby:2.4

MAINTAINER Valmik Roy <valmikroy@gmail.com>

RUN gem install bundle
ADD Gemfile  .
RUN bundle install --system
ADD . /tmp/<%= camel_name %>
WORKDIR /tmp/<%= camel_name %>

EXPOSE 8080

CMD ["rackup", "-q",  "config.ru"]
